language: c
before_script:
# We want to try perl standalone first
  - sudo apt-get update
  - sudo apt-get install cpanminus nsis
  - sudo cpanm --notest Archive::Tar Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy::Recursive File::Temp IPC::Run Perl::OSType
  - sh ./install-c-genericLogger.sh
script:
# We want to try perl standalone first
  - perl CMakeObjects.PL
  - rm -rf output
# ALL_IN_ONE
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make pack
  - cpack -G NSIS
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
# Not ALL_IN_ONE
  - cmake .
  - make check
  - make pack
  - cpack -G NSIS
  - sudo make install
  - tconv -f ASCII -t UTF-16 -o output/lib/tconv.tconv-UTF-16.c src/tconv.c
  - iconv -f ASCII -t UTF-16 -o output/lib/tconv.iconv-UTF-16.c src/tconv.c
  - uconv -f ASCII -t UTF-16 -o output/lib/tconv.uconv-UTF-16.c src/tconv.c
  - ls -l src/tconv.c output/lib/tconv.iconv-UTF-16.c output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - file src/tconv.c output/lib/tconv.iconv-UTF-16.c output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - diff output/lib/tconv.iconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - diff output/lib/tconv.uconv-UTF-16.c output/lib/tconv.tconv-UTF-16.c
  - tconv -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
